'use client'
import { useState } from 'react'
import { Rocket } from "lucide-react";
export default function BusinessCTAButtons() {
  const [isDownloading, setIsDownloading] = useState(false)
  const [downloadCount, setDownloadCount] = useState(25847)
  const [isSigningUp, setIsSigningUp] = useState(false)
  const [showEmailModal, setShowEmailModal] = useState(false)
  const [email, setEmail] = useState('')

  // Generate and download PDF with business plan
  const generateBusinessPlan = () => {
    const businessPlanContent = `
# FREE AI TOOLS BUSINESS IMPLEMENTATION PLAN 2025
## Your Complete Guide to 10X Productivity

### EXECUTIVE SUMMARY
This plan outlines how to implement 50+ free AI tools to boost business productivity by 10X and save $50,000+ annually.

### PHASE 1: FOUNDATION (Week 1-2)
**Essential Tools Setup:**
1. ChatGPT - Content creation and strategy
2. Google Workspace - Core operations
3. HubSpot Free CRM - Customer management
4. Canva - Visual design needs

**Expected Results:**
- 30% time savings in content creation
- Professional brand presence
- Organized customer data
- Estimated savings: $2,000/month

### PHASE 2: AUTOMATION (Week 3-4)  
**Process Automation:**
1. Calendly - Meeting scheduling
2. Slack - Team communication
3. Notion AI - Documentation
4. Zoom AI - Meeting intelligence

**Expected Results:**
- 50% reduction in administrative tasks
- Better team collaboration
- Automated workflows
- Additional savings: $1,500/month

### PHASE 3: SCALING (Month 2)
**Advanced Integration:**
1. LinkedIn Sales Navigator - Lead generation
2. Advanced ChatGPT workflows
3. Custom integrations
4. Team training programs

**Expected Results:**
- 40% increase in lead generation
- Streamlined operations
- Team-wide adoption
- Total monthly savings: $4,200

### ROI CALCULATOR
- Initial Investment: $0 (all free tools)
- Monthly Savings: $4,200
- Annual ROI: $50,400
- Payback Period: Immediate

### IMPLEMENTATION CHECKLIST
□ Sign up for essential tools (Week 1)
□ Team training sessions (Week 2)
□ Process documentation (Week 3)
□ Performance measurement (Week 4)
□ Scale and optimize (Month 2+)

### SUCCESS METRICS TO TRACK
- Hours saved per employee per week
- Cost reduction in software expenses
- Productivity improvements
- Customer satisfaction scores
- Revenue growth attribution

### RISK MITIGATION
- Data backup strategies
- Team training programs
- Gradual implementation approach
- Performance monitoring

### NEXT STEPS
1. Download this plan
2. Start with Phase 1 tools
3. Track your progress
4. Scale based on results
5. Join our community for support

---
Generated by TheToolsVerse.com - Your AI Tools Hub
Visit: https://thetoolsverse.com for more free resources
    `

    return businessPlanContent
  }

  const handleStartFree = async () => {
    setIsSigningUp(true)
    
    // Add analytics tracking
    if (typeof gtag !== 'undefined') {
      gtag('event', 'click_start_free', {
        event_category: 'CTA',
        event_label: 'Hero CTA Business Plan'
      })
    }
    
    // Simulate loading then redirect
    setTimeout(() => {
      window.open('https://thetoolsverse.com/get-started?ref=business-ai-plan', '_blank')
      setIsSigningUp(false)
    }, 1000)
  }

  const handleDownloadBusinessPlan = async () => {
    setIsDownloading(true)
    setDownloadCount(prev => prev + 1)
    
    try {
      // Generate PDF content
      const planContent = generateBusinessPlan()
      
      // Create PDF using jsPDF (you'll need to install: npm install jspdf)
      // For now, creating a text file that downloads as PDF
      const blob = new Blob([planContent], { type: 'text/plain' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `AI-Tools-Business-Plan-2025-${new Date().getFullYear()}.txt`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
      
      // Success feedback
      setTimeout(() => {
        alert('📥 Your Business Implementation Plan Downloaded Successfully! Check your downloads folder.')
        setIsDownloading(false)
      }, 1000)
      
      // Track download
      if (typeof gtag !== 'undefined') {
        gtag('event', 'download_business_plan', {
          event_category: 'Download',
          event_label: 'AI Tools Business Plan'
        })
      }
      
    } catch (error) {
      console.error('Download failed:', error)
      alert('❌ Download failed. Please try again or contact support.')
      setIsDownloading(false)
    }
  }

  const handleEmailSubmit = async (e) => {
    e.preventDefault()
    
    // Here you would normally send to your backend/email service
    console.log('Email submitted:', email)
    
    // Simulate API call
    setTimeout(() => {
      handleDownloadBusinessPlan()
      setShowEmailModal(false)
      setEmail('')
      alert('✅ Thanks! Your business plan is downloading now. Check your email for bonus resources!')
    }, 1000)
  }

  return (
    <>
      <div className="flex flex-col sm:flex-row gap-6 justify-center items-center">
        {/* Primary CTA - Start Free */}
        

        {/* Secondary CTA - Download Business Plan */}
        <button
          onClick={() => setShowEmailModal(true)}
          disabled={isDownloading}
          className="group relative cursor-pointer bg-white/20 backdrop-blur-lg hover:bg-white/30 text-white px-8 py-4 rounded-full text-lg font-semibold border border-white/30 transition-all duration-200 hover:border-white/50 disabled:opacity-70"
          aria-label="Download complete AI tools business implementation plan"
        >
          <div className="flex items-center justify-center space-x-2">
            {isDownloading ? (
              <>
                <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span>Generating Plan...</span>
              </>
            ) : (
              <>
                <span className="text-xl">📋</span>
                <span>Get Business Plan</span>
                <span className="bg-blue-500/80 cursor-pointer px-2 py-1 rounded-full text-sm ">FREE</span>
              </>
            )}
          </div>
          
          {/* Download counter */}
          <div className="absolute -top-2 -right-2 bg-red-500 text-white text-xs px-2 py-1 rounded-full">
            {downloadCount.toLocaleString()}+
          </div>
        </button>
      </div>

      {/* Email Capture Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl p-8 max-w-md w-full">
            <div className="text-center mb-6">
              <div className="text-4xl mb-4">📋</div>
              <h3 className="text-2xl font-bold text-gray-900 mb-2">
                Get Your FREE Business Implementation Plan
              </h3>
              <p className="text-gray-600">
                Complete step-by-step guide to implement AI tools and save $50,000+ annually
              </p>
            </div>

            <form onSubmit={handleEmailSubmit}>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="Enter your business email"
                className="w-full px-4 py-3 text-black border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 mb-4"
                required
              />
              
              <div className="bg-blue-50 p-4 rounded-lg mb-4">
                <h4 className="font-semibold text-blue-900 mb-2">Your Plan Includes:</h4>
                <ul className="text-sm text-blue-800 space-y-1">
                  <li>✅ Phase-wise implementation guide</li>
                  <li>✅ ROI calculator with projections</li>
                  <li>✅ Success metrics tracking</li>
                  <li>✅ Risk mitigation strategies</li>
                  <li>✅ Tool integration workflows</li>
                </ul>
              </div>
              
              <div className="flex space-x-3">
                <button
                  type="submit"
                  disabled={isDownloading}
                  className="flex-1 bg-blue-600 cursor-pointer hover:bg-blue-700 text-white py-3 rounded-lg font-semibold disabled:opacity-50"
                >
                  {isDownloading ? 'Generating...' : ' Download FREE Plan'}
                </button>
                
                <button
                  type="button"
                  onClick={() => setShowEmailModal(false)}
                  className="px-4 py-3 border cursor-pointer border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
              </div>
            </form>
            
            <p className="text-xs text-gray-500 mt-3 text-center">
              We respect your privacy. No spam, just valuable AI insights.
            </p>
          </div>
        </div>
      )}
    </>
  )
}
